spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: catalog-service-route
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/products/**,/api/v2/products/**
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
