spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: h2
  datasource:
    url: jdbc:h2:file:C:/Users/PC1/notification-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:60152
  cloud:
    function:
      definition: orderCreated
    stream:
      bindings:
        orderCreated-in-0:
          destination: orders
          content-type: application/json
          group: notification-service
          consumer:
            max-attempts: 5
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            back-off-max-interval: 30000
      kafka:
        bindings:
          orderCreated-in-0:
            consumer:
              enable-dlq: true
              # error.<destination>.<group>
              #dlq-name: orders.dlq.notification
server:
  port: 8082