services:
  discovery-server:
    image: tcell-discovery-server2:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - CONFIGURL=http://config-server:8787
      - SPRING_PROFILES_ACTIVE=dev
    depends_on: # container yeşil statuse geçti mi?
       config-server:
         condition: service_healthy
  config-server:
    image: config-srv:latest
    container_name: config-server
    ports:
      - "8787:8787"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8787/actuator/health"]
      interval: 3s
      timeout: 2s
      retries: 5
  db:
    image: postgres:15
    container_name: my-pg
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 3s
      retries: 10
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
  keycloak_db:
    image: postgres:15
    container_name: kc_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      timeout: 3s
      retries: 10
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    depends_on:
      keycloak_db:
        condition: service_healthy
    command:
      - start-dev
      - --http-port=8585
    ports:
      - "8585:8585"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

volumes:
  kc_pg_data: {}