spring:
  application:
    name: order-service
  cloud:
    function:
      definition: processOrder
    stream:
        bindings:
          orders-out-0:
            destination: orders
            content-type: application/json
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jdbc:
      dialect: h2
  datasource:
    url: jdbc:h2:file:C:/Users/PC1/order-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

# 15.15