spring:
  application:
    name: order-service
  cloud:
    function:
      definition: processOrder
    stream:
        bindings:
          processOrder-in-0:
            destination: orders
          processOrder-out-0:
            destination: payments

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

# 15.15