spring:
  application:
    name: backend-for-frontend
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/turkcell-microservices-dev
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bff-web
            client-secret: KnDyzTJ4gSC4W8258xicotWZCQN8vgZQ
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
server:
  port: 8989